# -*- python -*-
Import("env")

env.Program(["Footprint_1.cc"], LIBS=env.getlibs("detection"))
env.Program(["Measure_1.cc"], LIBS=env.getlibs("fw mwi detection"))
env.Program(["BBox_1.cc"], LIBS=env.getlibs("fw"))
#
# Tests
#
## import lsst.tests
## tests = lsst.tests.Control(env)

## tests.run("*.cc")
## for target in tests.run("*.py"):
##     env.Depends(target, "../python/lsst/detection/_detectionLib%s" % (env['LDMODULESUFFIX']))
