# -*- python -*-
Import("env")
import lsst.SConsUtils as scons

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base daf_data daf_persistence pex_logging pex_policy security afw")

env.LoadableModuleIncomplete("_detectionLib", Split("detectionLib.i"), LIBS=env.getlibs("detection"))
