# -*- python -*-
Import('env')

env.SharedLibrary(env['eups_product'], map(lambda str: "../src/" + str,
                                           ["DetectionSet.cc",
                                            "Footprint.cc",
                                            "Peak.cc",
                                            ]), LIBS=env.getlibs("mwi fw boost wcslib"))

